version: "3.5"
networks:
  go-starters-net:
    name: go-starters-net
    driver: bridge
services:
  db:
    image: "postgres:11"
    container_name: "go-starters"
    environment:
      POSTGRES_USER: starter
      POSTGRES_PASSWORD: starter
      POSTGRES_DB: go-mux-jwt-gorm-starter-db
      PGDATA: /pgdata
    networks:
      - go-starters-net
    ports:
      - "54325:5432"
    volumes:
      - .pgdata:/pgdata
